create table faq (
    id smallint generated by default as identity primary key,
    question text not null,
    aaron_take text,
    translation text not null,
    sort_order smallint not null
);

alter table faq enable row level security;

create policy "Public FAQ read"
    on faq for select to anon, authenticated
    using(true);