create type dietary as enum (
    'restriction',
    'preference',
    'none'
);

create type table_shape as enum (
    'round',
    'rectangular',
    'square'
);

create table guest_groups (
    id smallint generated by default as identity primary key,
    name text not null,
    custom_message text
);

create table seating_tables (
    id smallint generated by default as identity primary key,
    name text,
    capacity smallint,
    pos_x float,
    pos_y float,
    shape table_shape
);

create table guests (
    id smallint generated by default as identity primary key,
    group_id smallint references guest_groups(id),
    seating_table_id smallint references seating_tables(id),
    name text not null,
    attending boolean,
    contact_number text not null,
    address text,
    plus_one_allowed boolean not null,
    plus_one_name text,
    dietary_type dietary,
    dietary_details text[],
    song_request text,
    notes text
);